from CustomerChurn.logger import logging 
from CustomerChurn.exception import ChurnException
import sys
logging.info("DÃ©marrage du programme.")
logging.warning("Ceci est un avertissement.")
logging.error("Une erreur s'est produite.")
try:
    a=2/0
except Exception as e:
    raise ChurnException(e,sys)